### ISSUE TITLE
EspressifProvision[605:98077] This application is modifying the autolayout engine from a background thread after the engine was accessed from the main thread. This can lead to engine corruption and weird crashes.

### ISSUE THREAD

**Issue by coffice12** [espressif/esp-idf-provisioning-ios#10]
EspressifProvision[605:98077] This application is modifying the autolayout engine from a background thread after the engine was accessed from the main thread. This can lead to engine corruption and weird crashes.

**Comment by vikas-chandra-mnnit** [comment]
Hi @coffice12 Can you please confirm if you are running legacy iOS source or the new ESPProvisionSample?

**Comment by coffice12** [comment]
> Hi @coffice12 Can you please confirm if you are running legacy EspressifProvision project or the new ESPProvisionSample?

A brand new git clone download

**Comment by vikas-chandra-mnnit** [comment]
> > Hi @coffice12 Can you please confirm if you are running legacy EspressifProvision project or the new ESPProvisionSample?
> 
> A brand new git clone download

Okay but there are multiple projects within the repo. Which project are you trying to build?
