### ISSUE TITLE
WiFi scanning not working with example ESP BLE PROV iOS app.

### ISSUE THREAD

**Issue by yeetypete** [espressif/esp-idf-provisioning-ios#12]
I was testing the example ESP BLE Prov iOS app downloaded directly from the app store, but the app seems to get stuck on scanning for nearby WiFi networks. Could this be a bug? I have tried multiple iPhones and multiple ESP dev kits to make sure that is not the issue. I am flashing the example ble povisioning code from Espressif to the ESP dev kits. Attached below is a screenshot of the loading screen the app gets stuck on. Thanks for your help.

![image](https://user-images.githubusercontent.com/33677897/87879980-20d3af80-c9bc-11ea-8bb9-e3a906eef38a.png)

**Comment by vikas-chandra-mnnit** [comment]
Hi @yeetypete We are looking into this issue and will update you soon.

**Comment by vikas-chandra-mnnit** [comment]
@yeetypete We have fixed the issue and updated the app. Please download the latest version of ESP BLE Prov app from App Store to see the changes.

**Comment by yeetypete** [comment]
@vikas-chandra-mnnit Great thank you!

**Comment by rmrf1039** [comment]
This issue appears in my iPhone 12 as well. My IOS is running in 14.6. Does anyone have the same issue? I am pretty sure the ESP BLE Prov APP is in the latest version.

![IMG_1729](https://user-images.githubusercontent.com/33394453/122156829-5d45af00-ce9c-11eb-9704-ec384eb880f3.PNG)
