### ISSUE TITLE
Running with a custom Product ID

### ISSUE THREAD

**Issue by klisevich** [espressif/esp-idf-provisioning-ios#13]
Hi!
I'm struggling to run provisioning with a custom AWS account and AVS product id. I'm not an experienced iOS developer. Could you kindly provide example files with changes(what and where) that I should make in the iOS project to run with a custom product id?

**Comment by vikas-chandra-mnnit** [comment]
Hi @klisevich I have attached link of document for building the iOS app. I assume that you already know steps for generating API key so its not included in the link but other configuration steps are included. Let me know if you face any difficulties.
https://www.evernote.com/l/AZBdME3h_aVDbrqsjqVEM1i83-_cBrb1SAI

**Comment by klisevich** [comment]
> Hi @klisevich I have attached link of document for building the iOS app. I assume that you already know steps for generating API key so its not included in the link but other configuration steps are there. Let me know if you face any difficulties.
> https://www.evernote.com/l/AZBdME3h_aVDbrqsjqVEM1i83-_cBrb1SAI

Thank you, @vikas-chandra-mnnit ! It's very helpful!

**Comment by shahpiyushv** [comment]
Closing this issue since appropriate solution has been provided. Please fell free to reopen/file new issues if required.
