### ISSUE TITLE
Wi-Fi network list is always empty ?

### ISSUE THREAD

**Issue by iw2lsi** [espressif/esp-idf-provisioning-ios#17]
Hi,

  the app detects the BLE device in the right way but then, after the proof of possession, the Wi-Fi network list is always empty... I can press "Join Other Network" of course... but  a list of the available networks shouldn't be there ?

![IMG_9439](https://user-images.githubusercontent.com/1849408/97410881-e1dcc080-18ff-11eb-89af-b147b271cd8f.PNG)

        Giampaolo

**Comment by vikas-chandra-mnnit** [comment]
Hi @iw2lsi , This screen is supposed to show all the available Wi-Fi networks. We will need more information to look into this issue : 
1.  Are you able to successfully provision the device using `Join Other Network`
2. Are you able to see Wi-Fi list on your iPhone from the `Setting` app.
3. Are you using manual mode or QR code for provisioning.

Please revert back with these information. Thanks.

**Comment by iw2lsi** [comment]
Hi Vikas,


> Are you able to successfully provision the device using Join Other Network

yes

> Are you able to see Wi-Fi list on your iPhone from the Setting app.

yes... I can see at least five 2.4 GHz networks...

> Are you using manual mode or QR code for provisioning

manual mode... 

     thanks for the support,

            Giampaolo

**Comment by iw2lsi** [comment]
Hi Vikas,

>
>    1. App version.
>
> v2.0.5 (bcf81a2)


>
>    1. iOS version.
>
>
iOS v14.2 on a iPhone7

>
>    1. How frequent is this issue happening.
>
> always... I've never seen the list of available networks in more that 100
tests...


>
>    1. Attach BLE device logs if possible.
>
>
I'll try... can you tell me how to proceed ? should I just work from
menuconfig ?

**Comment by vikas-chandra-mnnit** [comment]
@iw2lsi, Can you confirm which example you are using for building the device? If you are using `legacy\ble_prov` it does not support  Wi-Fi scan list. In that case please use the relatively new example of `wifi_prov_mgr`. It has support of Wi-Fi scan and you change the transport to BLE using `menuconfig` command.

**Comment by iw2lsi** [comment]
Hi Vikas,

  I confirm that the list of available AP is shown using the example
provided in

    ~/esp-idf/examples/provisioning/manager

 while it does not appears using

   ~/esp-idf/examples/provisioning/ble_prov

BTW: ble_prov on iOS v12.2 gives the error: "get device version information
with error: The handle is invalid"... while it's working on an old Android
7.0 (app v2.0.3)

I'm on esp-idf branch "release/v4.0"
commit:fe67bedee29e40d4a46e19f4d275b2d821f1eb62... It's relatively old but
it's referred to by the esp-at project I'm using.

       Giampaolo



Il giorno mer 9 dic 2020 alle ore 17:12 Vikas Chandra <
notifications@github.com> ha scritto:

**Comment by iw2lsi** [comment]
Hi,

   issue seems resolved after switching to the wifi_prov_mgr approach... 

BTW: I had to set CONFIG_BTDM_CTRL_MODE_BLE_ONLY in order to make it work.

       Giampaolo
