### ISSUE TITLE
Xcode Compile Error (Swiftformat) - Incorporating provisioning into our own app

### ISSUE THREAD

**Issue by armandr** [espressif/esp-idf-provisioning-ios#2]
I get a compile error with the stock build of the provisioning downloaded from github:

> dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /usr/local/bin/swiftformat
  Reason: image not found
/Users/user/Library/Developer/Xcode/DerivedData/EspressifProvision-eevucoxlgqzszafraqmunebwumky/Build/Intermediates.noindex/EspressifProvision.build/BLESec1-Debug-iphonesimulator/EspressifProvision.build/Script-1487EBE92123D8C4007F44A6.sh: line 2: 68717 Abort trap: 6           swiftformat .
Command PhaseScriptExecution failed with a nonzero exit code

I have swiftformat installed along with the other requirements. xcode 10.2 on macos 10.14.

Regarding the requirements: what are minimum libraries/Pods that we need in order to incorporate the BLE provisioning into our own app?  (e.g. is swiftformat necessary?)

**Comment by armandr** [comment]
Update: for anyone else that runs into this.  Swiftformat does not seem to run in MacOs 10.14.3, after the 10.14.4 MacOs update it compiles.

**Comment by anujdeshpande** [comment]
Hi @armandr 
Thanks for pointing out. Indeed a lot of stuff has broken with the release of Swift 5. The `swift protobuf` library needs to be updated as well (they have a new release out). 

You can technically go ahead and remove any swift format dependencies, but I'd recommend you keep them. `swift-protobuf` is a hard dependency and you won't be able to proceed without it. 

We are in the process of releasing an updated version of the app with these changes where the version numbers will be bumped.

**Comment by anujdeshpande** [comment]
@armandr We've pushed a fix to `master` branch

**Comment by shahpiyushv** [comment]
Closing this issue, since it has been addressed long back.
