### ISSUE TITLE
Error while connecting to the device

### ISSUE THREAD

**Issue by maro01507i** [espressif/esp-idf-provisioning-ios#20]
Hello,

I'm having an issue while trying to connect to a created ESPDevice. The error is as follows:

First of all, after I'm connected to the device's network, I create the ESPDevice as follows:

```
ESPProvisionManager.shared.createESPDevice(
                deviceName: ssid, transport: .softap, completionHandler: { espDevice, _ in
                print("Device created")
                if espDevice != nil {
                     self.connectToDevice(espDevice)
                } else {
                       print("error")
                }
 })
```

This works great, but the problems comes when I try to connect to the device. The code for it is as follows:

```
espDevice?.connect { status in
            switch status {
            case .connected:
             print("success")
            case .disconnected:
             print("Disconnected")
            case let .failedToConnect(error):
                print("Failed to connect \(error)")
        }
}
```
In here sometimes an error comes thought the "failedToConnect" part, that is as follows:

> The Internet connection appears to be offline

My questions are as follows:

1. What is exactly that error?
2. Can I just ignore it and continue as if not error occurred, or it's a death-lock error?

Thanks in advance

**Comment by vikas-chandra-mnnit** [comment]
Hi @maro01507i, it seems that device connection is failing. Please confirm if you’re device has Proof of Possession capability. In that case please use the delegate method `ESPDeviceConnectionDelegate` to provide the correct POP information in the delegate method `getProofOfPossesion`. You can check ESPProvisionSample app source code for example.

**Comment by maro01507i** [comment]
Hello @vikas-chandra-mnnit . First of all, thanks for answering so quick. Second, I can confirm that we don't have any proof of possesion, but we have security set to 1 (secure).

If you want more detail:

```

char service_name[10];//15-10-20.
        get_device_service_name(service_name, sizeof(service_name));
        wifi_prov_security_t security = WIFI_PROV_SECURITY_1;


 

        /* Do we want a proof-of-possession (ignored if Security 0 is selected):
         *      - this should be a string with length > 0
         *      - NULL if not used
         */
        const char *pop = NULL;

 

        
        const char *service_key = "12345678";

 

        /* Start provisioning service */
        int32_t i32_result= wifi_prov_mgr_start_provisioning(security, pop, service_name, service_key);
```

**Comment by vikas-chandra-mnnit** [comment]
@maro01507i , Starting from iOS 13 you need to allow location permission in order for library to detect the SSID of the connected Wi-Fi. Also from iOS 14 permission of local network is required in order to interact with device locally. Please check if these permission are enabled in your app before connecting to the device. Let me know if it resolves your issue.

**Comment by maro01507i** [comment]
@vikas-chandra-mnnit Ok, after all looks like I was missing the local network permission for iOS 14. After granting that permission, looks like it's working without problems. I'm gonna close this issue for now, if in the future it reappears I'll let you know. Thanks for everthing
