### ISSUE TITLE
I use Object-c programming, how do I use the library?

### ISSUE THREAD

**Issue by JeremyChen1213** [espressif/esp-idf-provisioning-ios#23]
I use Object-c programming, how do I use the library? Attempt to mix, but failed, ask for help. Thanks

**Comment by vikas-chandra-mnnit** [comment]
Hi @JeremyChen1213 there are some good tutorials that can guide you for that. I can recommend one https://medium.com/@anum.amin/swift-pod-library-in-objective-c-project-c6d1c5af997d. However if you still find it hard to integrate, I will suggest to develop the provisioning module in your app using Swift and other module using Obj-C. Anyway if you find some issues with integration then let me know in this thread. We will try give resolution from our end.

**Comment by shahpiyushv** [comment]
Closing this issue since it has been answered.

**Comment by QuentinFarizon** [comment]
Still, an example would be great.

**Comment by zzdota** [comment]
> Hi @JeremyChen1213 there are some good tutorials that can guide you for that. I can recommend one https://medium.com/@anum.amin/swift-pod-library-in-objective-c-project-c6d1c5af997d. However if you still find it hard to integrate, I will suggest to develop the provisioning module in your app using Swift and other module using Obj-C. Anyway if you find some issues with integration then let me know in this thread. We will try to give resolution from our end.

Your library is written in swift and has not been adapted to Objective c (if you want to call properties or methods in swift in an Objective c project, at least @objc needs to be added to the code
etc.), I have tried many methods, but there is no way to use it normally. I hope to mention an Objective c project, an example of calling your swift library normally,an example would be great.

**Comment by Steven1937** [comment]
@zzdota Hi,  have u successfully integrated in Objective-C project?  thanks
