### ISSUE TITLE
Espressif 'master' library bug

### ISSUE THREAD

**Issue by DavidBeduzKalpa** [espressif/esp-idf-provisioning-ios#25]
We are using the Espressif library in https://github.com/espressif/esp-idf-provisioning-ios

Using the Espressif library, the provisioning doesn’t work. The process we use is calling:

SetData – to set the AVS parameters, after successful Amazon login.
Provision – to set the Wifi network SSID and password.
Launching the provision(ESPDevice.Provision()) the command blocks the device, which doesn’t reply to the command at all. We checked this at low (iOS peripheral) level: Debugging both the Espressif App () and the Espressif Library I saw the carachteristic used is different:

avsconfig – in library (but this is the characteristic to write the AVS configuration, NOT the Wifi settings!)
prov-config – in the test application (this seems to be the correct characteristic!)
Modifying the library to use prov-config during the wifi provision process instead of 'avsconfig' the provision process completes correctly. Please verify and update your library. NOTE: at a static code analysis it looks like the endpoint is correct (prov-config), but at runtime the call is done to 'avsconfig'

**Comment by vikas-chandra-mnnit** [comment]
@DavidBeduzKalpa Thanks for pointing this out. I can see in the library we are finding BLE characteristic using some pre defined keys. For provision we check if the path contains the key `config`. Storing BLE characteristic for avsconfig overrides it for prov-config because both contains the same substring `config`. In order to correct these we need to make strict check in our SDK. We will correct this in our next update. Again, thanks for reporting this issue to us.

**Comment by DavidBeduzKalpa** [comment]
@vikas-chandra-mnnit Thanks for the quick reply. When will the fixed library be released? Is there a date? For us the matter is quite urgent.
Thanks, a lot, David

**Comment by vikas-chandra-mnnit** [comment]
@DavidBeduzKalpa We will target to fix and push the library update by tomorrow EOD.

**Comment by vikas-chandra-mnnit** [comment]
@DavidBeduzKalpa We have updated the library and published the changes on SDK version 2.0.11. Please update your pod in order to get the latest release.

**Comment by DavidBeduzKalpa** [comment]
Great! Thank you!

Da: Vikas Chandra ***@***.***>
Data: martedì, 30 marzo 2021 16:36
A: espressif/esp-idf-provisioning-ios ***@***.***>
Cc: David Beduzzi ***@***.***>, Mention ***@***.***>
Oggetto: Re: [espressif/esp-idf-provisioning-ios] Espressif 'master' library bug (#25)

@DavidBeduzKalpa<https://github.com/DavidBeduzKalpa> We have updated the library and published the changes on SDK version 2.0.11. Please update your pod in order to get the latest release.
