### ISSUE TITLE
peripheralDisconnected not propagated in ESPProvision (IDFGH-5245)

### ISSUE THREAD

**Issue by stmariej** [espressif/esp-idf-provisioning-ios#28]
There is no way to know if the peripheral got disconnected because the delegate is not implemented.

extension ESPProvisionManager: ESPBLETransportDelegate {

	func peripheralConfigured(peripheral _: CBPeripheral) {}

	func peripheralNotConfigured(peripheral _: CBPeripheral) {}

	func peripheralDisconnected(peripheral: CBPeripheral, error _: Error?) {}

	func bluetoothUnavailable() {}
}

**Comment by vikas-chandra-mnnit** [comment]
@stmariej, Thanks for reporting this issue. We will look into it.

**Comment by vikas-chandra-mnnit** [comment]
@stmariej We have pushed a new version of ESPProvision library(2.0.12) with the above change. In order to receive BLE callbacks assign your ESPDevice instance `bleDelegate` property with the class object that conforms to ESPBLEDelegate protocol.

**Comment by stmariej** [comment]
Thanks!  I noticed the peripheral parameter is not populated in the peripheralConnected() in 2.0.12

public protocol ESPBLEDelegate {
    /// Peripheral associated with this ESPDevice is connected
    ///
    /// - Parameters:
    ///  - peripheral: CBPeripheral for which callback is recieved.
    func peripheralConnected()
