### ISSUE TITLE
Adding custom data

### ISSUE THREAD

**Issue by lph65724** [espressif/esp-idf-provisioning-ios#3]
Hi I would like to send custom data to the ESP32 besides wifi said and password, is there an example to show how I can do that?

Thank you

**Comment by oluckyman** [comment]
I ended up adding one more endpoint like in [custom_config](https://github.com/espressif/esp-idf/tree/master/examples/provisioning/custom_config) example ([this repo](https://github.com/oluckyman/esp-idf-ble_prov_and_custom_config) has it integrated into [ble_prov](https://github.com/espressif/esp-idf/tree/master/examples/provisioning/ble_prov) example).
For iOS part I generated swift structures from proto files. And passed them into `SendConfigData` the same way it done for wifi credentials:
```swift
let message = createCustomRequest(param1: "value1", param2: "value2")
transport.SendConfigData(path: Provision.CUSTOM_CONFIG_PATH, data: message) { response, error in
...
}
```
```swift
    private func createCustomRequest(param1: String, param2: String) throws -> Data? {
        var configData = CustomConfigRequest()
        configData.param1 = param1
        configData.param2 = param2
        return try security.encrypt(data: configData.serializedData())
    }
```

**Comment by shahpiyushv** [comment]
Closing this issue, since it has been addressed long back.

**Comment by ibrahimuslu** [comment]
I discovered an undocumented solution in the latest version of the Provisioning app. The ESPDevice Swift class includes an API for sending custom data to the device. You can find the custom data-sending API here: [custom-data sending api](https://github.com/espressif/esp-idf-provisioning-ios/blob/ff70c09ded605969e053ade44a6b8756b93c4e4c/ESPProvision/ESPDevice.swift#L254)
