### ISSUE TITLE
ESP SoftAP Prov App on the Appstore iOS 15.1 not working

### ISSUE THREAD

**Issue by spaceMan00** [espressif/esp-idf-provisioning-ios#41]
I have a fresh install of the app on iOS 15. As soon as I press connect it takes me to the Settings pages
![IMG_8133](https://user-images.githubusercontent.com/970119/147471183-942b2925-49bf-42c7-8130-54fa1927bd6b.PNG)
As you can see I have all permissions allowed. 
I am not getting a prompt to enable local network permission and it doesn't even show up in the app settings. 
Please help.

**Comment by iw2lsi** [comment]
same behaviour here... using iOS 15.2.1 on an iPhone7...

**Comment by vikas-chandra-mnnit** [comment]
Hi, @spaceMan00 @iw2lsi app setting is the default landing page when we redirect to the Settings app from our Provisioning application. In the `Settings` app go to Wi-Fi and connect with SSID having the same name as your ESP device. After that come back to your ESP SoftAP Prov app and it will redirect you to the next step of provisioning.

**Comment by iw2lsi** [comment]
Hi,

   nothing new here... I know that I have to connect to the right SSID...

          Giampaolo
