### ISSUE TITLE
Failed to initialise session with the device.

### ISSUE THREAD

**Issue by guiqiang107** [espressif/esp-idf-provisioning-ios#50]
![251652081061_ pic](https://user-images.githubusercontent.com/8225765/167360574-3c34616f-7bc1-40f9-85ef-0459cdf55fe3.jpg)
![261652081061_ pic](https://user-images.githubusercontent.com/8225765/167360604-fde37efc-59b7-44cd-a1b4-a40523d684bd.jpg)
![271652081062_ pic](https://user-images.githubusercontent.com/8225765/167360617-9958673c-c8bd-403c-be3f-a13b47860a76.jpg)

**Comment by guiqiang107** [comment]
16:28:33.653 | ESPDevice.connect(delegate:completionHandler:) (151) : Connecting ESPDevice...
16:28:33.654 | ESPDevice.connect(delegate:completionHandler:) (162) : Start connecting SoftAp device.
16:28:33.660 | ESPDevice.connectToSoftApUsingCredentials(ssid:completionHandler:) (177) : Successfully conected to SoftAP.
16:28:33.661 | ESPSoftAPTransport.SendConfigData(path:data:completionHandler:) (114) : Send config data to path proto-ver
16:28:33.661 | ESPSoftAPTransport.SendHTTPData(path:data:completionHandler:) (61) : Sending HTTP data to device..
16:28:33.662 | ESPSoftAPTransport.SendHTTPData(path:data:completionHandler:) (72) : URLSession request initiated with data...3 bytes
16:28:33.692 | ESPSoftAPTransport.SendHTTPData(path:data:completionHandler:) (75) : Processing response..
16:28:33.693 | ESPSoftAPTransport.SendHTTPData(path:data:completionHandler:) (86) : HTTP request successful.
16:28:33.694 | ESPDevice.processVersionInfoResponse(response:error:completionHandler:) (514) : Process version info start
16:28:33.694 | ESPDevice.processVersionInfoResponse(response:error:completionHandler:) (523) : Process version info success
16:28:33.695 | ESPDevice.initialiseSession(sessionPath:completionHandler:) (426) : Initialise session
16:28:33.695 | ESPDevice.initSecureSession(sessionPath:pop:completionHandler:) (463) : Initialise session security 1
16:28:33.696 | ESPSecurity1.init(proofOfPossession:) (56) : Initailising secure class with proof of possession.
16:28:33.696 | ESPSecurity1.generateKeyPair() (131) : Generating key pair for encrypting data.
16:28:33.696 | ESPSecurity1.generatePrivateKey() (117) : Generating random private key.
16:28:33.700 | ESPDevice.initSession(sessionPath:completionHandler:) (469) : Init session
16:28:33.704 | ESPSession.init(transport:security:) (53) : Initialising session class with transport: ESPProvision.ESPSoftAPTransport and security: ESPProvision.ESPSecurity1
16:28:33.705 | ESPSession.initialize(response:sessionPath:completionHandler:) (67) : Initializing the session handshake to establish a secure session with the device.
16:28:33.705 | ESPSecurity1.getNextRequestInSession(data:) (68) : Getting next request in session.
16:28:33.707 | ESPSession.initialize(response:sessionPath:completionHandler:) (70) : session intialize
16:28:33.707 | ESPSoftAPTransport.SendSessionData(data:sessionPath:completionHandler:) (99) : Sending session data.
16:28:33.707 | ESPSoftAPTransport.SendHTTPData(path:data:completionHandler:) (61) : Sending HTTP data to device..
16:28:33.707 | ESPSoftAPTransport.SendHTTPData(path:data:completionHandler:) (72) : URLSession request initiated with data...41 bytes
2022-05-09 16:28:33.746480+0800 ESP PROV SAMPLE[25772:6599743] Task <98F63C15-B6DA-458C-8D77-9EE54CE5281B>.<3> HTTP load failed, 345/0 bytes (error code: -1005 [4:-4])
2022-05-09 16:28:33.750958+0800 ESP PROV SAMPLE[25772:6599740] Task <98F63C15-B6DA-458C-8D77-9EE54CE5281B>.<3> finished with error [-1005] Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." UserInfo={_kCFStreamErrorCodeKey=-4, NSUnderlyingError=0x282e5d470 {Error Domain=kCFErrorDomainCFNetwork Code=-1005 "(null)" UserInfo={NSErrorPeerAddressKey=<CFData 0x2803fc8c0 [0x20ccd41b8]>{length = 16, capacity = 16, bytes = 0x10020050c0a804010000000000000000}, _kCFStreamErrorCodeKey=-4, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <98F63C15-B6DA-458C-8D77-9EE54CE5281B>.<3>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <98F63C15-B6DA-458C-8D77-9EE54CE5281B>.<3>"
), NSLocalizedDescription=The network connection was lost., NSErrorFailingURLStringKey=http://192.168.4.1:80/prov-session,

**Comment by shushant43** [comment]
Were you able to solve this?

**Comment by MaksymSolomkin** [comment]
I have same problem
