### ISSUE TITLE
Connection to device twice causes app to freeze

### ISSUE THREAD

**Issue by tobyloki** [espressif/esp-idf-provisioning-ios#51]
I tap on a device to pair, but select cancel pairing. Then I tap on the device again, and the app freezes. How can I fix this problem?

Steps to reproduce:
1. Download code at commit fbad43fb51d8b678fd860742befc41741c3f0ad2 (should be the latest as of 5/10/22)
2. Navigate to the page for scanning BLE devices
3. After a device has been found, tap on it. Click cancel pairing
4. Tap on the device again. Now the app is frozen and I can't press any of the menu buttons.

Here is a video showing the steps I described above.
https://user-images.githubusercontent.com/35203563/167766440-7fd216e8-5b1e-4366-96dd-51bc8ae993b8.mp4

**Comment by vikas-chandra-mnnit** [comment]
Hi @tobyloki, I am trying to reproduce this issue on my end. Please provide some additional details:

1. ESP-IDF version.
2. iOS version.
3. Firmware logs if possible.

**Comment by tobyloki** [comment]
This issue is resolved when I upgrade the ESPProvision pod version from 2.0.12 to 2.0.15.
