### ISSUE TITLE
Cannot run sample project, "No such module 'ESPProvision'" Error in ConnectViewController

### ISSUE THREAD

**Issue by maribeee** [espressif/esp-idf-provisioning-ios#57]
## Description

I'm attempting to run your sample ios code so that I can test our ESP device, however I cannot get the code to build within XCode at all. Any time I build, even though ESPProvision was successfully installed via `pod install` I get the following error:

`No such module 'ESPProvision'`

The error appears in the file `/ESPProvisionSample/Provision/ConnectViewController.swift`

I see that the pod exists in `/Pods/Pods/ESPProvision` so it seems to have loaded successfully

However maybe it isn't building? I do not see it in `/ESPProvisionSample/Frameworks`

I attempted to build the library separately by going to `Product -> Scheme -> New Scheme` and selecting `ESPProvision` from the list, and it built successfully, however when I tried to build the sample project again, I once again got the same no such module error.

I am running the app using the generated `.xcworkspace` file so that is not the issue

I get no further error logging beyond saying that ESPProvision module could not be found.

I have also tried clearing derived data and re-installing the pods and that didn't help either

**To Reproduce**
1. Download repo and CD into ESPProvisionSample folder
2. Run `pod install` (Results in successful installation)
3. Run build, build fails with the error "No such module 'ESPProvision'" even though the pod install was successful

... 

**Frequency**
Consistently every time I try to build

**Expected behavior**
App builds successfully and pops up a simulated view of app in the simulator

**Screenshots**

**ESP Device Information:**
Have not even gotten to this point yet

**iOS information:**
- xcode 13.4.1, attempted building for multiple simulated device types

**Additional context**
I haven't edited the code at all just trying to run the code as-is from your repo right now

**Comment by GabrielRobinsonAzevedo** [comment]
I'm getting the same error with Xcode 14, how can i solve it?

**Comment by vikas-chandra-mnnit** [comment]
Hi @GabrielRobinsonAzevedo, This issue occurs if we try to build the Sample App for iOS simulator. We will look into it in detail meanwhile you can run the sample apps on iOS physical device instead. Project will build successfully for iOS physical devices.
