### ISSUE TITLE
There is an incorrect method in ESPWiFiManager and ESPThreadManager

### ISSUE THREAD

**Issue by SkyOfFeather** [espressif/esp-idf-provisioning-ios#81]
WiFi list scan failed. After log analysis, I found that there was an error in the method in one area

In ESPWiFiManager and ESPThreadManager
``` swift
    private func processStartScan(responseData: Data) {
        let decryptedResponse = (security.encrypt(data: responseData))!
        do {
            _ = try NetworkScanPayload(serializedData: decryptedResponse)
        } catch {
            delegate?.wifiScanFinished(wifiList: nil, error: .scanRequestError(error))
        }
    }
```

```security.encrypt(data: responseData)```Should be```security.decrypt(data: responseData)```

**Comment by ajay-gantayet** [comment]
Hi @SkyOfFeather ,  thanks for bringing this to our attention. Actually after processStartScan we also call the getWiFiScanStatus and getThreadScanStatus, which also provides us as response the list of scanned wifi and thread networks. And the provisioning also continues. Hence we probably missed this in our testing.

We will fix this and push out a new SDK version soon.
