### ISSUE TITLE
unable to open file (in target "ESPProvision" in project "ESPProvision")

### ISSUE THREAD

**Issue by zhaochengwei** [espressif/esp-idf-provisioning-ios#9]
when I comiple in xcode Version 11.5 (11E608c),
esp-idf-provisioning-ios/Pods/Target Support Files/Pods-ESPProvision/Pods-ESPProvision.debug.xcconfig: unable to open file (in target "ESPProvision" in project "ESPProvision")
![image](https://user-images.githubusercontent.com/13081827/86805532-85346c00-c0aa-11ea-86f0-01add2e9acc1.png)

branch:master

**Comment by lapumb-spindance** [comment]
Try:
1. Close xcode
2. execute `pod update` in the ESPProvisionSample directory
3. Re-open the project, build

**Comment by vikas-chandra-mnnit** [comment]
Hi @zhaochengwei I see you are trying to build the ESPProvision library. To do so you need to follow few steps:

1. Close Xcode
2. In the terminal change directory to the path where you have cloned the repo.
3. Do `pod install` and open the ESPProvision.xcworkspace.
4. You need to have Info.plist file that is missing currently in project directory. I have attached it extract by unzipping.  Do add it in your Xcode project and build.
[Info.plist.zip](https://github.com/espressif/esp-idf-provisioning-ios/files/4886655/Info.plist.zip)

**Comment by coffice12** [comment]
> Hi @zhaochengwei I see you are trying to build the ESPProvision library. To do so you need to follow few steps:
> 
> 1. Close Xcode
> 2. In the terminal change directory to the path where you have cloned the repo.
> 3. Do `pod install` and open the ESPProvision.xcworkspace.
> 4. You need to have Info.plist file that is missing currently in project directory. I have attached it extract by unzipping.  Do add it in your Xcode project and build.
>    [Info.plist.zip](https://github.com/espressif/esp-idf-provisioning-ios/files/4886655/Info.plist.zip)

Or wrong

**Comment by zhaochengwei** [comment]
> Hi @zhaochengwei I see you are trying to build the ESPProvision library. To do so you need to follow few steps:
> 
> 1. Close Xcode
> 2. In the terminal change directory to the path where you have cloned the repo.
> 3. Do `pod install` and open the ESPProvision.xcworkspace.
> 4. You need to have Info.plist file that is missing currently in project directory. I have attached it extract by unzipping.  Do add it in your Xcode project and build.
>    [Info.plist.zip](https://github.com/espressif/esp-idf-provisioning-ios/files/4886655/Info.plist.zip)

Thanks, I solve the problem。And if possible, had better add this step into readme .
